.pragma library

// per-control search index for the Hub's search bar. sectionDefs (Hub.qml)
// only gives the search bar page names to match against ("Shell", "Desktop
// Widgets"), so a query for a word that names an individual control --
// "weather", "seconds", "gaps" -- never found anything unless it happened to
// also appear in a page name. This is the fix: one entry per meaningfully
// fixed, persistent settings control across every Hub page (and tab, where a
// page has tabs), each carrying keywords a user would plausibly type that
// don't literally appear in the on-screen label. Scored by
// fuzzy.js's rankSettings() against label + keywords.
//
// tab is null for untabbed pages; otherwise the tab's `key` in that page's
// own Segmented model. Deliberately skips anything data-driven/per-item with
// no fixed identity (a live Wi-Fi network list, an installed-addon list, a
// user-authored window rule) -- those get one generic entry for the concept
// instead of one per dynamic row.
var entries = [
    { section: "general", tab: null, label: "24-hour clock", keywords: ["time", "clock", "military time", "12 hour", "format", "hour"] },
    { section: "general", tab: null, label: "Weather location", keywords: ["weather", "location", "city", "geocode", "forecast", "temperature", "auto locate", "ip"] },
    { section: "general", tab: null, label: "Weather units", keywords: ["weather", "temperature", "celsius", "fahrenheit", "degrees", "units"] },

    { section: "shell", tab: "frame", label: "Enable frame", keywords: ["frame", "border", "screen edge", "toggle"] },
    { section: "shell", tab: "frame", label: "Border thickness", keywords: ["frame", "border", "thickness", "width", "gaps"] },
    { section: "shell", tab: "frame", label: "OSD & toast corner", keywords: ["osd", "toast", "notification", "corner", "radius", "rounding"] },
    { section: "shell", tab: "frame", label: "OSD opacity", keywords: ["osd", "toast", "opacity", "transparency"] },
    { section: "shell", tab: "frame", label: "Show Caps/Num/Scroll Lock OSD", keywords: ["capslock", "numlock", "scrolllock", "osd", "indicator", "lock key flash"] },

    { section: "shell", tab: "global", label: "Inner roundness", keywords: ["roundness", "corner", "radius", "rounded", "shell-wide"] },
    { section: "shell", tab: "global", label: "Frame corner", keywords: ["frame", "corner", "radius", "roundness"] },
    { section: "shell", tab: "global", label: "Edge melt", keywords: ["edge", "melt", "smoothing", "frame"] },
    { section: "shell", tab: "global", label: "Shadow strength", keywords: ["shadow", "strength", "intensity"] },
    { section: "shell", tab: "global", label: "Shadow size", keywords: ["shadow", "size", "blur", "spread"] },
    { section: "shell", tab: "global", label: "Brand name", keywords: ["brand", "name", "wordmark", "identity", "ryoku"] },
    { section: "shell", tab: "global", label: "Brand text mark", keywords: ["mark", "glyph", "text", "brand", "logo", "symbol"] },
    { section: "shell", tab: "global", label: "Brand logo image", keywords: ["logo", "image", "icon", "brand", "mark", "svg", "png"] },
    { section: "shell", tab: "global", label: "Tint image to accent", keywords: ["tint", "accent", "colour", "logo", "image"] },
    { section: "shell", tab: "global", label: "Surface colour", keywords: ["surface", "colour", "color", "background", "fill"] },
    { section: "shell", tab: "global", label: "Surface opacity", keywords: ["surface", "opacity", "transparency"] },
    { section: "shell", tab: "global", label: "Font", keywords: ["font", "typeface", "family", "text", "nerd font"] },
    { section: "shell", tab: "global", label: "Font size", keywords: ["font", "size", "scale", "text"] },

    { section: "shell", tab: "bar", label: "Enable bar", keywords: ["bar", "enable", "toggle", "taskbar", "panel"] },
    { section: "shell", tab: "bar", label: "Bar position", keywords: ["bar", "position", "top", "bottom"] },
    { section: "shell", tab: "bar", label: "Bar style", keywords: ["bar", "style", "skin", "theme", "noctalia", "caelestia", "aegis", "stele", "triptych", "delos", "nacre", "inir", "aurora", "angel"] },
    { section: "shell", tab: "bar", label: "Bar thickness", keywords: ["bar", "thickness", "height", "size"] },
    { section: "shell", tab: "bar", label: "Focused window title", keywords: ["window", "title", "bar", "focused"] },
    { section: "shell", tab: "bar", label: "Now playing (bar)", keywords: ["media", "music", "now playing", "bar"] },
    { section: "shell", tab: "bar", label: "Network speed (bar)", keywords: ["network", "speed", "wifi", "bar", "bandwidth"] },
    { section: "shell", tab: "bar", label: "System stats (bar)", keywords: ["cpu", "ram", "memory", "temp", "temperature", "stats", "bar"] },
    { section: "shell", tab: "bar", label: "Agent usage (bar)", keywords: ["claude", "agent", "usage", "ai", "bar"] },
    { section: "shell", tab: "bar", label: "Status glyphs", keywords: ["status", "network", "battery", "inbox", "icons", "bar"] },
    { section: "shell", tab: "bar", label: "Weather (bar)", keywords: ["weather", "bar", "temperature", "condition"] },
    { section: "shell", tab: "bar", label: "Display (bar)", keywords: ["display", "brightness", "backlight", "vibrance", "bar"] },
    { section: "shell", tab: "bar", label: "Only occupied workspaces", keywords: ["workspace", "occupied", "bar", "hide empty"] },
    { section: "shell", tab: "bar", label: "Per-window workspace icons", keywords: ["workspace", "icons", "apps", "bar"] },
    { section: "shell", tab: "bar", label: "Island roundness", keywords: ["island", "radius", "roundness", "delos"] },
    { section: "shell", tab: "bar", label: "Island modules", keywords: ["island", "module", "delos", "workspaces", "clock", "date", "media", "title", "status", "tray"] },

    { section: "shell", tab: "sidebar", label: "Enable left sidebar", keywords: ["sidebar", "left", "enable", "aside"] },
    { section: "shell", tab: "sidebar", label: "Stash pane", keywords: ["stash", "sidebar", "left", "pane"] },
    { section: "shell", tab: "sidebar", label: "Enable right sidebar", keywords: ["sidebar", "right", "enable", "aside"] },
    { section: "shell", tab: "sidebar", label: "Notifications pane", keywords: ["notifications", "sidebar", "right"] },
    { section: "shell", tab: "sidebar", label: "Calendar pane", keywords: ["calendar", "sidebar", "right"] },
    { section: "shell", tab: "sidebar", label: "Media pane", keywords: ["media", "sidebar", "right", "now playing"] },
    { section: "shell", tab: "sidebar", label: "Weather pane", keywords: ["weather", "sidebar", "right"] },
    { section: "shell", tab: "sidebar", label: "Recording pane", keywords: ["recording", "sidebar", "right", "screen capture"] },
    { section: "shell", tab: "sidebar", label: "Open on hover", keywords: ["hover", "click", "sidebar", "behaviour", "clickless"] },
    { section: "shell", tab: "sidebar", label: "Quick toggles", keywords: ["quick toggle", "sidebar", "controls", "wifi", "bluetooth", "mic", "dnd", "night light", "airplane", "tablet", "webcam", "lid sleep"] },
    { section: "shell", tab: "sidebar", label: "Sidebar width", keywords: ["sidebar", "width", "size"] },
    { section: "shell", tab: "sidebar", label: "Sidebar corner hotspot", keywords: ["sidebar", "corner", "hotspot", "trigger"] },

    { section: "shell", tab: "visualizer", label: "Visualiser style", keywords: ["visualizer", "visualiser", "style", "bars", "dots", "monitor", "wave", "segments", "radial", "circle"] },
    { section: "shell", tab: "visualizer", label: "Visualiser position", keywords: ["visualizer", "visualiser", "position", "layout"] },
    { section: "shell", tab: "visualizer", label: "Visualiser shape", keywords: ["visualizer", "visualiser", "shape", "rounded", "flat"] },
    { section: "shell", tab: "visualizer", label: "Visualiser mirror", keywords: ["visualizer", "visualiser", "mirror"] },
    { section: "shell", tab: "visualizer", label: "Visualiser enabled", keywords: ["visualizer", "visualiser", "enable", "toggle", "spectrum"] },
    { section: "shell", tab: "visualizer", label: "Visualiser bar count", keywords: ["visualizer", "visualiser", "bars", "count"] },
    { section: "shell", tab: "visualizer", label: "Visualiser segments", keywords: ["visualizer", "visualiser", "segments"] },
    { section: "shell", tab: "visualizer", label: "Visualiser peak caps", keywords: ["visualizer", "visualiser", "peaks", "caps"] },
    { section: "shell", tab: "visualizer", label: "Visualiser height", keywords: ["visualizer", "visualiser", "height", "size"] },
    { section: "shell", tab: "visualizer", label: "Visualiser bar width", keywords: ["visualizer", "visualiser", "width", "thickness"] },
    { section: "shell", tab: "visualizer", label: "Visualiser bloom", keywords: ["visualizer", "visualiser", "bloom", "glow"] },
    { section: "shell", tab: "visualizer", label: "Visualiser reflection", keywords: ["visualizer", "visualiser", "reflection", "glow"] },
    { section: "shell", tab: "visualizer", label: "Visualiser smoothing", keywords: ["visualizer", "visualiser", "smoothing", "feel"] },
    { section: "shell", tab: "visualizer", label: "Visualiser sensitivity", keywords: ["visualizer", "visualiser", "sensitivity", "gain"] },
    { section: "shell", tab: "visualizer", label: "Visualiser frame rate", keywords: ["visualizer", "visualiser", "fps", "framerate", "motion"] },
    { section: "shell", tab: "visualizer", label: "Visualiser adaptive quality", keywords: ["visualizer", "visualiser", "adaptive", "quality", "performance"] },
    { section: "shell", tab: "visualizer", label: "Visualiser idle wave", keywords: ["visualizer", "visualiser", "idle", "wave", "at rest"] },

    { section: "widgets", tab: "clock", label: "Clock widget enabled", keywords: ["clock widget", "enable", "desktop clock"] },
    { section: "widgets", tab: "clock", label: "Clock face", keywords: ["clock", "face", "design", "digital", "analog", "minimal", "flip", "rings"] },
    { section: "widgets", tab: "clock", label: "Clock accent", keywords: ["clock", "accent", "colour", "wallust", "brand", "mono"] },
    { section: "widgets", tab: "clock", label: "Show seconds", keywords: ["clock", "seconds", "time", "format"] },
    { section: "widgets", tab: "clock", label: "Show date", keywords: ["clock", "date", "calendar"] },
    { section: "widgets", tab: "clock", label: "Date style", keywords: ["clock", "date", "style", "inline", "badge", "stacked"] },
    { section: "widgets", tab: "clock", label: "Clock size", keywords: ["clock", "size", "scale"] },
    { section: "widgets", tab: "clock", label: "Clock background", keywords: ["clock", "background", "card", "glass"] },
    { section: "widgets", tab: "clock", label: "Clock corner radius", keywords: ["clock", "corner", "radius", "rounding"] },
    { section: "widgets", tab: "clock", label: "Clock opacity", keywords: ["clock", "opacity", "transparency"] },
    { section: "widgets", tab: "clock", label: "Clock anchor", keywords: ["clock", "anchor", "placement", "position", "desktop"] },
    { section: "widgets", tab: "clock", label: "Clock position (X/Y)", keywords: ["clock", "position", "x", "y", "coordinates", "drag"] },
    { section: "widgets", tab: "clock", label: "Lock clock on desktop", keywords: ["clock", "lock", "desktop", "drag"] },

    { section: "widgets", tab: "weather", label: "Weather widget location", keywords: ["weather", "location", "city", "desktop widget", "general"] },
    { section: "widgets", tab: "weather", label: "Weather widget enabled", keywords: ["weather widget", "enable", "desktop weather"] },
    { section: "widgets", tab: "weather", label: "Weather widget design", keywords: ["weather", "design", "card", "minimal", "strip"] },
    { section: "widgets", tab: "weather", label: "Weather widget unit", keywords: ["weather", "unit", "celsius", "fahrenheit", "temperature"] },
    { section: "widgets", tab: "weather", label: "Weather forecast scope", keywords: ["weather", "forecast", "today", "week"] },
    { section: "widgets", tab: "weather", label: "Weather live animations", keywords: ["weather", "animation", "live"] },
    { section: "widgets", tab: "weather", label: "Weather widget size", keywords: ["weather", "size", "scale"] },
    { section: "widgets", tab: "weather", label: "Weather widget background", keywords: ["weather", "background", "card", "glass"] },
    { section: "widgets", tab: "weather", label: "Weather widget corner radius", keywords: ["weather", "corner", "radius"] },
    { section: "widgets", tab: "weather", label: "Weather widget opacity", keywords: ["weather", "opacity"] },
    { section: "widgets", tab: "weather", label: "Weather widget anchor", keywords: ["weather", "anchor", "placement", "position", "desktop"] },
    { section: "widgets", tab: "weather", label: "Weather widget position (X/Y)", keywords: ["weather", "position", "x", "y", "coordinates", "drag"] },
    { section: "widgets", tab: "weather", label: "Lock weather widget on desktop", keywords: ["weather", "lock", "desktop", "drag"] },

    { section: "widgets", tab: "calendar", label: "Calendar widget enabled", keywords: ["calendar widget", "enable", "desktop calendar"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget design", keywords: ["calendar", "design", "month", "minimal", "agenda", "week", "heatmap"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget accent", keywords: ["calendar", "accent", "colour"] },
    { section: "widgets", tab: "calendar", label: "Week starts on", keywords: ["calendar", "week", "start", "monday", "sunday"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget size", keywords: ["calendar", "size", "scale"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget background", keywords: ["calendar", "background", "card", "glass"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget corner radius", keywords: ["calendar", "corner", "radius"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget opacity", keywords: ["calendar", "opacity"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget anchor", keywords: ["calendar", "anchor", "placement", "position", "desktop"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget position (X/Y)", keywords: ["calendar", "position", "x", "y", "coordinates", "drag"] },
    { section: "widgets", tab: "calendar", label: "Lock calendar widget on desktop", keywords: ["calendar", "lock", "desktop", "drag"] },

    { section: "displays", tab: null, label: "Enabled", keywords: ["disable", "turn off", "power state", "active display", "monitor on/off", "screen on"] },
    { section: "displays", tab: null, label: "Resolution", keywords: ["mode", "screen size", "pixel dimensions", "display mode", "width height"] },
    { section: "displays", tab: null, label: "Scale", keywords: ["scaling", "dpi", "zoom", "hidpi", "display scale"] },
    { section: "displays", tab: null, label: "Rotation", keywords: ["orientation", "rotate", "portrait", "landscape", "screen rotation"] },
    { section: "displays", tab: null, label: "Adaptive sync", keywords: ["vrr", "variable refresh rate", "freesync", "g-sync", "tearing", "adaptive sync"] },
    { section: "displays", tab: null, label: "Mirror of", keywords: ["mirror", "clone", "duplicate display", "screen mirroring"] },
    { section: "displays", tab: null, label: "Position X", keywords: ["x coordinate", "placement", "monitor position", "layout position", "horizontal position"] },
    { section: "displays", tab: null, label: "Position Y", keywords: ["y coordinate", "placement", "monitor position", "layout position", "vertical position"] },
    { section: "input", tab: null, label: "Layout", keywords: ["keyboard layout", "xkb layout", "language layout", "locale", "keymap"] },
    { section: "input", tab: null, label: "Style", keywords: ["variant", "keyboard variant", "azerty", "dvorak", "layout style"] },
    { section: "input", tab: null, label: "Second layout", keywords: ["secondary layout", "alternate keyboard", "multilingual", "second keymap"] },
    { section: "input", tab: null, label: "Switch layouts", keywords: ["layout switch shortcut", "toggle layout", "language switch key", "keyboard switch chord"] },
    { section: "input", tab: null, label: "Numlock on at login", keywords: ["numlock", "number lock", "numeric keypad", "num lock default"] },
    { section: "input", tab: null, label: "Caps Lock", keywords: ["capslock remap", "caps lock behavior", "escape remap", "ctrl remap"] },
    { section: "input", tab: null, label: "Swap Alt and Super", keywords: ["alt win swap", "super key", "windows key", "meta key", "command key swap"] },
    { section: "input", tab: null, label: "Compose key", keywords: ["compose key", "dead key", "special characters", "unicode input"] },
    { section: "input", tab: null, label: "Extra options", keywords: ["xkb options", "raw keyboard options", "advanced keyboard settings", "custom options"] },
    { section: "input", tab: null, label: "Sensitivity", keywords: ["mouse speed", "pointer speed", "cursor speed", "mouse sensitivity"] },
    { section: "input", tab: null, label: "Follow mouse", keywords: ["focus follows mouse", "hover focus", "mouse focus", "sloppy focus"] },
    { section: "input", tab: null, label: "Acceleration", keywords: ["mouse acceleration", "pointer acceleration", "accel profile", "cursor acceleration"] },
    { section: "input", tab: null, label: "Left-handed buttons", keywords: ["left handed mouse", "button swap", "southpaw", "reverse buttons"] },
    { section: "input", tab: null, label: "Natural scroll (mouse)", keywords: ["reverse scrolling", "scroll direction", "invert scroll", "natural scrolling"] },
    { section: "input", tab: null, label: "Scroll speed (mouse)", keywords: ["mouse wheel speed", "scroll sensitivity", "wheel scroll speed"] },
    { section: "input", tab: null, label: "Middle-click pastes", keywords: ["middle click paste", "primary selection", "clipboard paste", "middle button paste"] },
    { section: "input", tab: null, label: "Natural scroll (touchpad)", keywords: ["reverse scrolling", "scroll direction", "invert scroll", "natural scrolling"] },
    { section: "input", tab: null, label: "Tap to click", keywords: ["tap click", "touchpad tap", "tap-to-click"] },
    { section: "input", tab: null, label: "Tap and drag", keywords: ["drag lock", "tap drag", "touchpad drag"] },
    { section: "input", tab: null, label: "Disable while typing", keywords: ["dwt", "palm rejection", "typing disable", "keyboard typing touchpad"] },
    { section: "input", tab: null, label: "Click by finger count", keywords: ["clickfinger", "two finger right click", "three finger middle click", "finger count click"] },
    { section: "input", tab: null, label: "Emulate middle click", keywords: ["middle click emulation", "three finger click", "middle button emulation"] },
    { section: "input", tab: null, label: "Scroll speed (touchpad)", keywords: ["touchpad scroll speed", "scroll sensitivity", "wheel scroll speed"] },
    { section: "input", tab: null, label: "Swipe between workspaces", keywords: ["workspace swipe", "gesture navigation", "touchpad gestures", "workspace switching gesture"] },
    { section: "input", tab: null, label: "Swipe fingers", keywords: ["finger count", "gesture fingers", "3 finger 4 finger", "swipe finger count"] },
    { section: "input", tab: null, label: "Natural swipe direction", keywords: ["swipe invert", "gesture direction", "natural gesture"] },
    { section: "input", tab: null, label: "Swipe past the last workspace to add one", keywords: ["create workspace swipe", "infinite workspaces", "new workspace gesture", "auto create workspace"] },
    { section: "input", tab: null, label: "Swipe distance", keywords: ["gesture distance", "swipe threshold", "gesture sensitivity"] },
    { section: "input", tab: null, label: "Repeat rate", keywords: ["key repeat rate", "keyboard repeat speed", "autorepeat rate"] },
    { section: "input", tab: null, label: "Repeat delay", keywords: ["repeat delay", "key repeat delay", "initial delay", "autorepeat delay"] },
    { section: "input", tab: null, label: "Flip webcam 180°", keywords: ["webcam flip", "camera upside down", "camera orientation", "flip camera", "invert camera"] },
    { section: "connections", tab: "wifi", label: "Wi-Fi", keywords: ["wifi on off", "wireless toggle", "wlan", "radio toggle", "wifi enable"] },
    { section: "connections", tab: "bluetooth", label: "Bluetooth", keywords: ["bluetooth on off", "adapter toggle", "radio toggle", "wireless toggle", "bt enable"] },
    { section: "connections", tab: "hotspot", label: "Hotspot", keywords: ["hotspot on off", "wifi sharing", "tethering", "access point", "share connection"] },
    { section: "connections", tab: "hotspot", label: "Network name", keywords: ["ssid", "hotspot name", "wifi name", "network id"] },
    { section: "connections", tab: "hotspot", label: "Password", keywords: ["hotspot password", "wpa2 password", "wifi password", "shared key"] },
    { section: "gpu", tab: null, label: "Graphics mode", keywords: ["gpu mode", "hybrid performance passthrough", "graphics switching", "optimus", "prime", "gpu selection"] },
    { section: "recording", tab: null, label: "Framerate", keywords: ["fps", "frame rate", "video framerate", "recording fps"] },
    { section: "recording", tab: null, label: "Framerate mode", keywords: ["cfr vfr", "constant framerate", "variable framerate", "frame rate mode"] },
    { section: "recording", tab: null, label: "Quality", keywords: ["video quality", "bitrate", "recording quality", "encode quality"] },
    { section: "recording", tab: null, label: "Codec", keywords: ["video codec", "h264 hevc av1", "compression format", "encoding format"] },
    { section: "recording", tab: null, label: "Encoder", keywords: ["hardware encoder", "gpu cpu encoding", "video encoder", "encoding backend"] },
    { section: "recording", tab: null, label: "Show the cursor in recordings", keywords: ["cursor recording", "mouse pointer capture", "show cursor", "record cursor"] },
    { section: "dictation", tab: null, label: "Voice typing", keywords: ["dictation toggle", "voice typing on off", "speech to text enable", "voxtype enable"] },
    { section: "dictation", tab: null, label: "Engine & model", keywords: ["stt engine", "whisper model", "transcription engine", "voice model", "speech recognition engine"] },
    { section: "dictation", tab: null, label: "API key", keywords: ["openai key", "api token", "credentials", "cloud engine key", "openai api key"] },

    { section: "updates", tab: null, label: "Automatic update checks", keywords: ["update interval", "auto update", "check frequency", "schedule", "update schedule", "hourly", "daily", "weekly", "auto check", "update channel"] },

    { section: "appearance", tab: "look", label: "Corner radius", keywords: ["radius", "rounding", "corner", "roundness", "window corners"] },
    { section: "appearance", tab: "look", label: "Corner softness", keywords: ["rounding power", "corner curve", "squircle", "corner shape", "softness"] },
    { section: "appearance", tab: "look", label: "Border thickness", keywords: ["border width", "border size", "outline thickness", "window border"] },
    { section: "appearance", tab: "look", label: "Tiling layout", keywords: ["layout", "dwindle", "master", "scrolling", "tiling mode", "window arrangement"] },
    { section: "appearance", tab: "look", label: "Column width", keywords: ["scrolling layout", "column size", "hyprscrolling", "width"] },
    { section: "appearance", tab: "look", label: "Scroll to follow focus", keywords: ["scrolling", "follow focus", "auto scroll", "hyprscrolling"] },
    { section: "appearance", tab: "look", label: "Inner gaps", keywords: ["gaps", "spacing", "window gap", "padding between windows", "inner gap"] },
    { section: "appearance", tab: "look", label: "Outer gaps", keywords: ["gaps", "screen edge", "monitor edge", "outer gap", "margin"] },
    { section: "appearance", tab: "look", label: "Drag to resize at window edges", keywords: ["resize", "border drag", "window edge resize", "click drag resize"] },
    { section: "appearance", tab: "look", label: "Snap floating windows", keywords: ["window snapping", "edge snap", "magnetism", "align windows"] },
    { section: "appearance", tab: "look", label: "Window title bars", keywords: ["titlebar", "hyprbars", "window bar", "title bar"] },
    { section: "appearance", tab: "look", label: "Title bar height", keywords: ["titlebar height", "hyprbars", "bar size"] },
    { section: "appearance", tab: "look", label: "Title bar text size", keywords: ["titlebar font size", "text size", "hyprbars", "font"] },
    { section: "appearance", tab: "look", label: "Blur the title bar", keywords: ["titlebar blur", "hyprbars", "blur"] },
    { section: "appearance", tab: "look", label: "Title bar buttons", keywords: ["window controls", "close button", "maximise button", "hyprbars"] },
    { section: "appearance", tab: "look", label: "Active window opacity", keywords: ["opacity", "transparency", "focused window", "active opacity"] },
    { section: "appearance", tab: "look", label: "Inactive window opacity", keywords: ["opacity", "transparency", "unfocused window", "inactive opacity"] },
    { section: "appearance", tab: "look", label: "Dim inactive windows", keywords: ["dimming", "unfocused dim", "inactive dim", "fade unfocused"] },
    { section: "appearance", tab: "look", label: "Dim strength", keywords: ["dim amount", "dimming intensity", "inactive opacity", "unfocused darkness"] },
    { section: "appearance", tab: "look", label: "Blur enabled", keywords: ["window blur", "background blur", "toggle blur"] },
    { section: "appearance", tab: "look", label: "Blur size", keywords: ["blur radius", "blur amount", "blur strength"] },
    { section: "appearance", tab: "look", label: "Blur passes", keywords: ["blur quality", "blur iterations", "blur passes"] },
    { section: "appearance", tab: "look", label: "X-ray", keywords: ["xray blur", "see through blur", "wallpaper through blur", "transparent blur"] },
    { section: "appearance", tab: "look", label: "Blur vibrancy", keywords: ["blur saturation", "vibrancy", "colour intensity blur"] },
    { section: "appearance", tab: "look", label: "Blur noise", keywords: ["grain", "blur noise", "texture", "dithering"] },
    { section: "appearance", tab: "look", label: "Window shadows", keywords: ["drop shadow", "shadow toggle", "window shadow"] },
    { section: "appearance", tab: "look", label: "Shadow range", keywords: ["shadow size", "shadow distance", "shadow spread"] },
    { section: "appearance", tab: "look", label: "Shadow sharpness", keywords: ["shadow power", "shadow softness", "shadow falloff"] },
    { section: "appearance", tab: "look", label: "Animations", keywords: ["animation toggle", "motion", "transitions", "enable animations"] },
    { section: "appearance", tab: "look", label: "Wobbly windows", keywords: ["wobble", "jelly windows", "window wobble effect"] },
    { section: "appearance", tab: "look", label: "Open / close", keywords: ["open animation", "close animation", "pop", "slide", "gnome style", "window style"] },
    { section: "appearance", tab: "look", label: "Glow behind windows", keywords: ["glow effect", "window halo", "backlight glow"] },
    { section: "appearance", tab: "look", label: "Glow range", keywords: ["glow size", "glow distance", "halo size"] },
    { section: "appearance", tab: "look", label: "Glow colour", keywords: ["glow color", "halo color"] },
    { section: "appearance", tab: "look", label: "Liquid glass windows", keywords: ["hyprglass", "glassmorphism", "glass effect", "frosted glass"] },
    { section: "appearance", tab: "look", label: "Glass preset", keywords: ["hyprglass preset", "glass style", "clear", "subtle", "contrast"] },
    { section: "appearance", tab: "look", label: "Glass blur strength", keywords: ["hyprglass blur", "glass distortion"] },
    { section: "appearance", tab: "look", label: "Glass opacity", keywords: ["hyprglass opacity", "glass transparency"] },
    { section: "appearance", tab: "borders", label: "Active window border colour", keywords: ["border color", "focused border", "active border color"] },
    { section: "appearance", tab: "borders", label: "Inactive window border colour", keywords: ["border color", "unfocused border", "inactive border color"] },
    { section: "appearance", tab: "borders", label: "Rotating gradient border", keywords: ["gradient border", "rotating border", "rainbow border", "animated border"] },
    { section: "appearance", tab: "borders", label: "Rotation speed", keywords: ["gradient speed", "animated border speed", "border animation speed"] },
    { section: "appearance", tab: "borders", label: "Image border around windows", keywords: ["imgborders", "picture border", "custom border image"] },
    { section: "appearance", tab: "borders", label: "Border scale", keywords: ["imgborders", "border image size", "tiling scale"] },
    { section: "appearance", tab: "borders", label: "Smooth scaling", keywords: ["imgborders", "antialiasing", "smooth image", "filter"] },
    { section: "appearance", tab: "cursor", label: "Cursor theme", keywords: ["cursor icon set", "pointer theme", "icon theme"] },
    { section: "appearance", tab: "cursor", label: "Cursor size", keywords: ["pointer size", "cursor scale"] },
    { section: "appearance", tab: "cursor", label: "Hide after idle", keywords: ["auto-hide cursor", "idle timeout", "hide pointer", "inactivity timeout", "cursor idle"] },
    { section: "appearance", tab: "cursor", label: "Hide while typing", keywords: ["auto-hide on keypress", "pointer hide typing", "cursor hide typing"] },
    { section: "appearance", tab: "cursor", label: "Realistic cursor motion", keywords: ["dynamiccursors", "cursor animation", "physics cursor"] },
    { section: "appearance", tab: "cursor", label: "Cursor motion style", keywords: ["rotate", "tilt", "stretch", "dynamiccursors", "pointer style"] },
    { section: "appearance", tab: "cursor", label: "Shake to find", keywords: ["magnify cursor", "find my cursor", "shake mouse", "cursor locate"] },
    { section: "appearance", tab: "wallpaper", label: "Theme palette colours", keywords: ["colour scheme", "light dark", "follow wallpaper", "wallust", "palette mode"] },
    { section: "appearance", tab: "comfort", label: "Backlight brightness", keywords: ["backlight", "display brightness", "panel brightness", "screen brightness"] },
    { section: "appearance", tab: "comfort", label: "Vibrance saturation", keywords: ["saturation", "colour intensity", "screen vibrance"] },
    { section: "appearance", tab: "comfort", label: "Warm the screen", keywords: ["blue light filter", "warm screen", "redshift", "night light", "nightlight"] },
    { section: "appearance", tab: "comfort", label: "Night light temperature", keywords: ["colour temperature", "warmth", "kelvin", "blue light"] },

    { section: "launcher", tab: null, label: "Corner radius", keywords: ["radius", "rounding", "corner", "launcher shape"] },
    { section: "launcher", tab: null, label: "Background blur", keywords: ["backdrop blur", "launcher blur", "blur amount"] },
    { section: "launcher", tab: null, label: "Weather units", keywords: ["celsius", "fahrenheit", "temperature unit", "weather"] },
    { section: "launcher", tab: null, label: "Show weather", keywords: ["weather widget", "home card weather"] },
    { section: "launcher", tab: null, label: "Show greeting", keywords: ["greeting message", "welcome text", "home card greeting"] },
    { section: "launcher", tab: null, label: "Backdrop strength", keywords: ["hero image opacity", "backdrop opacity", "launcher background strength"] },

    { section: "fastfetch", tab: null, label: "Emblem type", keywords: ["logo type", "image", "ascii", "builtin", "none", "fastfetch logo"] },
    { section: "fastfetch", tab: null, label: "Logo width", keywords: ["fastfetch logo size", "emblem width"] },
    { section: "fastfetch", tab: null, label: "Logo height", keywords: ["fastfetch logo size", "emblem height"] },
    { section: "fastfetch", tab: null, label: "Logo padding", keywords: ["fastfetch logo spacing", "emblem padding"] },
    { section: "fastfetch", tab: null, label: "Readout accent", keywords: ["fastfetch colour", "accent colour", "terminal readout colour"] },

    { section: "animations", tab: null, label: "Animations", keywords: ["animation toggle", "enable animations", "motion", "transitions", "global animations"] },
    { section: "animations", tab: null, label: "Animate the focused window", keywords: ["hyprfocus", "focus animation", "window focus effect", "focus flash"] },
    { section: "animations", tab: null, label: "Focus flash style", keywords: ["flash", "bounce", "slide", "hyprfocus mode"] },
    { section: "animations", tab: null, label: "Flash opacity", keywords: ["hyprfocus", "focus flash intensity"] },
    { section: "animations", tab: null, label: "Bounce strength", keywords: ["hyprfocus", "focus bounce amount"] },
    { section: "animations", tab: null, label: "Slide height", keywords: ["hyprfocus", "focus slide distance"] },

    { section: "addons", tab: null, label: "Enable/disable plugin", keywords: ["addon", "add-on", "plugin", "enable", "disable", "toggle on", "widget", "extension"] },
    { section: "addons", tab: null, label: "Show as", keywords: ["host", "placement", "frame popout", "desktop widget", "widget location", "display as", "popout"] },
    { section: "windowrules", tab: null, label: "Window rules", keywords: ["float", "tile", "pin", "fullscreen", "maximize", "center", "size", "move", "workspace", "opacity", "blur", "border", "shadow", "rounding", "corners", "dim", "animations", "opaque", "xray", "focus", "idle", "sleep", "class", "title", "match window", "custom rule"] },
    { section: "appoverrides", tab: null, label: "App overrides", keywords: ["per-app", "per application", "class", "title", "match window", "window rule", "override", "app-specific", "custom look"] },
    { section: "appoverrides", tab: null, label: "Opacity", keywords: ["transparency", "alpha", "translucent", "see-through"] },
    { section: "appoverrides", tab: null, label: "Corners", keywords: ["radius", "rounding", "corner", "roundness", "round corners"] },
    { section: "appoverrides", tab: null, label: "Border", keywords: ["border size", "outline", "edge", "border width", "stroke"] },
    { section: "appoverrides", tab: null, label: "Blur", keywords: ["backdrop blur", "background blur", "frosted glass"] },
    { section: "appoverrides", tab: null, label: "Shadow", keywords: ["drop shadow", "window shadow"] },
    { section: "appoverrides", tab: null, label: "Dim inactive", keywords: ["dim", "inactive window", "unfocused", "darken", "fade unfocused"] },
    { section: "appoverrides", tab: null, label: "Animations", keywords: ["animation", "motion", "transition", "noanim"] },
    { section: "appoverrides", tab: null, label: "Force opaque", keywords: ["opaque", "force opacity", "remove transparency", "solid background"] },
    { section: "layerrules", tab: null, label: "Layer rules", keywords: ["namespace", "bar", "launcher", "notification", "layer shell", "blur", "dim around", "lockscreen", "above lock", "xray", "ignore alpha", "surface"] },
    { section: "autostart", tab: null, label: "Autostart", keywords: ["startup", "login", "boot", "launch at start", "run on login", "startup command", "autostart command"] },
    { section: "environment", tab: null, label: "Environment variables", keywords: ["env var", "environment variable", "export", "name value pair", "session variable"] },
    { section: "performance", tab: null, label: "Low power mode", keywords: ["potato mode", "battery saver", "low power", "performance mode", "reduce effects", "laptop battery", "weak gpu"] },
    { section: "performance", tab: null, label: "Reduce motion", keywords: ["motion", "animation", "transitions", "instant", "accessibility", "reduce animation"] },
    { section: "performance", tab: null, label: "Disable blur", keywords: ["blur off", "backdrop blur", "gpu", "turn off blur", "no blur"] },
    { section: "performance", tab: null, label: "Disable shadows", keywords: ["shadow off", "drop shadow", "no shadow", "window shadow"] },
    { section: "performance", tab: null, label: "Hide desktop widgets while covered", keywords: ["desktop widget", "memory", "unload widget", "hide widget", "covered windows", "free memory"] },
    { section: "performance", tab: null, label: "Freeze visualiser when idle", keywords: ["audio visualizer", "spectrum", "waveform", "freeze animation", "idle", "no audio"] },
    { section: "performance", tab: null, label: "Unload visualiser when silent", keywords: ["audio visualizer", "memory", "unload", "silent", "no audio", "free memory"] },
    { section: "performance", tab: null, label: "Freeze bar bead animation", keywords: ["glowing bead", "bar animation", "pill animation", "idle bar", "statusbar"] },
    { section: "performance", tab: null, label: "Unload launcher when idle", keywords: ["app launcher", "memory", "unload", "idle", "free memory", "drun"] },
    { section: "performance", tab: null, label: "Unload overview when idle", keywords: ["workspace overview", "memory", "unload", "idle", "free memory", "expo", "overview mode"] },
    { section: "rashin", tab: null, label: "Start Rashin with desktop", keywords: ["rashin daemon", "agent os", "enable rashin", "local agent", "vault", "enable daemon", "autostart daemon"] },
    { section: "keybinds", tab: "custom", label: "Custom keybinds", keywords: ["shortcut", "hotkey", "bind", "keybind", "hyprland bind", "custom shortcut", "key combo"] }
];
