.pragma library

// per-control search index for the Hub's search bar. sectionDefs (Hub.qml)
// only gives the search bar page names to match against ("Shell", "Desktop
// Widgets"), so a query for a word that names an individual control --
// "weather", "seconds", "gaps" -- never found anything unless it happened to
// also appear in a page name. This is the fix: one entry per meaningfully
// fixed, persistent settings control across every Hub page (and tab, where a
// page has tabs), each carrying keywords a user would plausibly type that
// don't literally appear in the on-screen label. Scored by
// fuzzy.js's rankSettings() against label + keywords.
//
// tab is null for untabbed pages; otherwise the tab's `key` in that page's
// own Segmented model. Deliberately skips anything data-driven/per-item with
// no fixed identity (a live Wi-Fi network list, an installed-addon list, a
// user-authored window rule) -- those get one generic entry for the concept
// instead of one per dynamic row.
//
// highlight is optional: when a page's SettingSection sets a matching
// highlightId, clicking this result flashes and scrolls to that group (see
// HubHighlight.qml). Omit it for a page/tab that doesn't have one yet --
// navigation still works, it just lands on the page without a flash.
var entries = [
    { section: "general", tab: null, label: "24-hour clock", highlight: "time_24h", keywords: ["time", "clock", "military time", "12 hour", "format", "hour"] },
    { section: "general", tab: null, label: "Show seconds", highlight: "time_seconds", keywords: ["clock", "seconds", "time", "format", "bar", "menu bar"] },
    { section: "general", tab: null, label: "Weather location", highlight: "general_weather_location", keywords: ["weather", "location", "city", "geocode", "forecast", "temperature", "auto locate", "ip"] },
    { section: "general", tab: null, label: "Weather units", highlight: "weather_units", keywords: ["weather", "temperature", "celsius", "fahrenheit", "degrees", "units"] },

    { section: "shell", tab: "frame", label: "Enable frame", highlight: "frame_enable", keywords: ["frame", "border", "screen edge", "toggle"] },
    { section: "shell", tab: "frame", label: "Border thickness", highlight: "frame_border", keywords: ["frame", "border", "thickness", "width", "gaps"] },
    { section: "shell", tab: "frame", label: "OSD & toast corner", highlight: "frame_osd_corner", keywords: ["osd", "toast", "notification", "corner", "radius", "rounding"] },
    { section: "shell", tab: "frame", label: "OSD opacity", highlight: "frame_osd_opacity", keywords: ["osd", "toast", "opacity", "transparency"] },
    { section: "shell", tab: "frame", label: "Show Caps/Num/Scroll Lock OSD", highlight: "frame_osd_lockkeys", keywords: ["capslock", "numlock", "scrolllock", "osd", "indicator", "lock key flash"] },

    { section: "shell", tab: "global", label: "Inner roundness", highlight: "global_inner_roundness", keywords: ["roundness", "corner", "radius", "rounded", "shell-wide"] },
    { section: "shell", tab: "global", label: "Frame corner", highlight: "global_frame_corner", keywords: ["frame", "corner", "radius", "roundness"] },
    { section: "shell", tab: "global", label: "Edge melt", highlight: "global_edge_melt", keywords: ["edge", "melt", "smoothing", "frame"] },
    { section: "shell", tab: "global", label: "Shadow strength", highlight: "global_shadow_strength", keywords: ["shadow", "strength", "intensity"] },
    { section: "shell", tab: "global", label: "Shadow size", highlight: "global_shadow_size", keywords: ["shadow", "size", "blur", "spread"] },
    { section: "shell", tab: "global", label: "Brand name", highlight: "global_brand_name", keywords: ["brand", "name", "wordmark", "identity", "ryoku"] },
    { section: "shell", tab: "global", label: "Brand text mark", highlight: "global_brand_textmark", keywords: ["mark", "glyph", "text", "brand", "logo", "symbol"] },
    { section: "shell", tab: "global", label: "Brand logo image", highlight: "global_brand_logo", keywords: ["logo", "image", "icon", "brand", "mark", "svg", "png"] },
    { section: "shell", tab: "global", label: "Tint image to accent", highlight: "global_brand_tint", keywords: ["tint", "accent", "colour", "logo", "image"] },
    { section: "shell", tab: "global", label: "Surface colour", highlight: "global_surface_colour", keywords: ["surface", "colour", "color", "background", "fill"] },
    { section: "shell", tab: "global", label: "Surface opacity", highlight: "global_surface_opacity", keywords: ["surface", "opacity", "transparency"] },
    { section: "shell", tab: "global", label: "Font", highlight: "global_text_font", keywords: ["font", "typeface", "family", "text", "nerd font"] },
    { section: "shell", tab: "global", label: "Font size", highlight: "global_text_size", keywords: ["font", "size", "scale", "text"] },

    { section: "shell", tab: "bar", label: "Enable bar", highlight: "bar_enable", keywords: ["bar", "enable", "toggle", "taskbar", "panel"] },
    { section: "shell", tab: "bar", label: "Bar position", highlight: "bar_position", keywords: ["bar", "position", "top", "bottom"] },
    { section: "shell", tab: "bar", label: "Bar style", highlight: "bar_style", keywords: ["bar", "style", "skin", "theme", "noctalia", "caelestia", "aegis", "stele", "triptych", "delos", "nacre", "inir", "aurora", "angel"] },
    { section: "shell", tab: "bar", label: "Bar thickness", highlight: "bar_thickness", keywords: ["bar", "thickness", "height", "size"] },
    { section: "shell", tab: "bar", label: "Focused window title", highlight: "bar_content_title", keywords: ["window", "title", "bar", "focused"] },
    { section: "shell", tab: "bar", label: "Now playing (bar)", highlight: "bar_content_media", keywords: ["media", "music", "now playing", "bar"] },
    { section: "shell", tab: "bar", label: "Network speed (bar)", highlight: "bar_content_netspeed", keywords: ["network", "speed", "wifi", "bar", "bandwidth"] },
    { section: "shell", tab: "bar", label: "System stats (bar)", highlight: "bar_content_stats", keywords: ["cpu", "ram", "memory", "temp", "temperature", "stats", "bar"] },
    { section: "shell", tab: "bar", label: "Agent usage (bar)", highlight: "bar_content_agent", keywords: ["claude", "agent", "usage", "ai", "bar"] },
    { section: "shell", tab: "bar", label: "Status glyphs", highlight: "bar_content_status", keywords: ["status", "network", "battery", "inbox", "icons", "bar"] },
    { section: "shell", tab: "bar", label: "Weather (bar)", highlight: "bar_content_weather", keywords: ["weather", "bar", "temperature", "condition"] },
    { section: "shell", tab: "bar", label: "Display (bar)", highlight: "bar_content_display", keywords: ["display", "brightness", "backlight", "vibrance", "bar"] },
    { section: "shell", tab: "bar", label: "Only occupied workspaces", highlight: "bar_content_occupied", keywords: ["workspace", "occupied", "bar", "hide empty"] },
    { section: "shell", tab: "bar", label: "Per-window workspace icons", highlight: "bar_content_workspaceicons", keywords: ["workspace", "icons", "apps", "bar"] },
    { section: "shell", tab: "bar", label: "Island roundness", highlight: "bar_island_roundness", keywords: ["island", "radius", "roundness", "delos"] },
    { section: "shell", tab: "bar", label: "Island modules", highlight: "bar_island_modules", keywords: ["island", "module", "delos", "workspaces", "clock", "date", "media", "title", "status", "tray"] },

    { section: "shell", tab: "sidebar", label: "Enable left sidebar", highlight: "sidebar_left_enable", keywords: ["sidebar", "left", "enable", "aside"] },
    { section: "shell", tab: "sidebar", label: "Stash pane", highlight: "sidebar_left_stash", keywords: ["stash", "sidebar", "left", "pane"] },
    { section: "shell", tab: "sidebar", label: "Enable right sidebar", highlight: "sidebar_right_enable", keywords: ["sidebar", "right", "enable", "aside"] },
    { section: "shell", tab: "sidebar", label: "Notifications pane", highlight: "sidebar_right_notifications", keywords: ["notifications", "sidebar", "right"] },
    { section: "shell", tab: "sidebar", label: "Calendar pane", highlight: "sidebar_right_calendar", keywords: ["calendar", "sidebar", "right"] },
    { section: "shell", tab: "sidebar", label: "Media pane", highlight: "sidebar_right_media", keywords: ["media", "sidebar", "right", "now playing"] },
    { section: "shell", tab: "sidebar", label: "Weather pane", highlight: "sidebar_right_weather", keywords: ["weather", "sidebar", "right"] },
    { section: "shell", tab: "sidebar", label: "Recording pane", highlight: "sidebar_right_recording", keywords: ["recording", "sidebar", "right", "screen capture"] },
    { section: "shell", tab: "sidebar", label: "Open on hover", highlight: "sidebar_behaviour_hover", keywords: ["hover", "click", "sidebar", "behaviour", "clickless"] },
    { section: "shell", tab: "sidebar", label: "Quick toggles", highlight: "sidebar_quick_toggles", keywords: ["quick toggle", "sidebar", "controls", "wifi", "bluetooth", "mic", "dnd", "night light", "airplane", "tablet", "webcam", "lid sleep"] },
    { section: "shell", tab: "sidebar", label: "Sidebar width", highlight: "sidebar_size_width", keywords: ["sidebar", "width", "size"] },
    { section: "shell", tab: "sidebar", label: "Sidebar corner hotspot", highlight: "sidebar_size_hotspot", keywords: ["sidebar", "corner", "hotspot", "trigger"] },

    { section: "shell", tab: "visualizer", label: "Visualiser style", highlight: "viz_style", keywords: ["visualizer", "visualiser", "style", "bars", "dots", "monitor", "wave", "segments", "radial", "circle"] },
    { section: "shell", tab: "visualizer", label: "Visualiser position", highlight: "viz_layout_position", keywords: ["visualizer", "visualiser", "position", "layout"] },
    { section: "shell", tab: "visualizer", label: "Visualiser shape", highlight: "viz_layout_shape", keywords: ["visualizer", "visualiser", "shape", "rounded", "flat"] },
    { section: "shell", tab: "visualizer", label: "Visualiser mirror", highlight: "viz_layout_mirror", keywords: ["visualizer", "visualiser", "mirror"] },
    { section: "shell", tab: "visualizer", label: "Visualiser enabled", highlight: "viz_spectrum_enabled", keywords: ["visualizer", "visualiser", "enable", "toggle", "spectrum"] },
    { section: "shell", tab: "visualizer", label: "Visualiser bar count", highlight: "viz_spectrum_bars", keywords: ["visualizer", "visualiser", "bars", "count"] },
    { section: "shell", tab: "visualizer", label: "Visualiser segments", highlight: "viz_spectrum_segments", keywords: ["visualizer", "visualiser", "segments"] },
    { section: "shell", tab: "visualizer", label: "Visualiser peak caps", highlight: "viz_spectrum_peaks", keywords: ["visualizer", "visualiser", "peaks", "caps"] },
    { section: "shell", tab: "visualizer", label: "Visualiser height", highlight: "viz_size_height", keywords: ["visualizer", "visualiser", "height", "size"] },
    { section: "shell", tab: "visualizer", label: "Visualiser bar width", highlight: "viz_size_barwidth", keywords: ["visualizer", "visualiser", "width", "thickness"] },
    { section: "shell", tab: "visualizer", label: "Visualiser bloom", highlight: "viz_glow_bloom", keywords: ["visualizer", "visualiser", "bloom", "glow"] },
    { section: "shell", tab: "visualizer", label: "Visualiser reflection", highlight: "viz_glow_reflection", keywords: ["visualizer", "visualiser", "reflection", "glow"] },
    { section: "shell", tab: "visualizer", label: "Visualiser smoothing", highlight: "viz_feel_smoothing", keywords: ["visualizer", "visualiser", "smoothing", "feel"] },
    { section: "shell", tab: "visualizer", label: "Visualiser sensitivity", highlight: "viz_feel_sensitivity", keywords: ["visualizer", "visualiser", "sensitivity", "gain"] },
    { section: "shell", tab: "visualizer", label: "Visualiser frame rate", highlight: "viz_motion_framerate", keywords: ["visualizer", "visualiser", "fps", "framerate", "motion"] },
    { section: "shell", tab: "visualizer", label: "Visualiser adaptive quality", highlight: "viz_motion_adaptive", keywords: ["visualizer", "visualiser", "adaptive", "quality", "performance"] },
    { section: "shell", tab: "visualizer", label: "Visualiser idle wave", highlight: "viz_at_rest_idle", keywords: ["visualizer", "visualiser", "idle", "wave", "at rest"] },

    { section: "widgets", tab: "clock", label: "Clock widget enabled", highlight: "clock_widget_enabled", keywords: ["clock widget", "enable", "desktop clock"] },
    { section: "widgets", tab: "clock", label: "Clock face", highlight: "clock_widget_face", keywords: ["clock", "face", "design", "digital", "analog", "minimal", "flip", "rings"] },
    { section: "widgets", tab: "clock", label: "Clock accent", highlight: "clock_widget_accent", keywords: ["clock", "accent", "colour", "wallust", "brand", "mono"] },
    { section: "widgets", tab: "clock", label: "Show date", highlight: "clock_date_show", keywords: ["clock", "date", "calendar"] },
    { section: "widgets", tab: "clock", label: "Date style", highlight: "clock_date_style", keywords: ["clock", "date", "style", "inline", "badge", "stacked"] },
    { section: "widgets", tab: "clock", label: "Clock size", highlight: "clock_size_scale", keywords: ["clock", "size", "scale"] },
    { section: "widgets", tab: "clock", label: "Clock background", highlight: "clock_size_bg", keywords: ["clock", "background", "card", "glass"] },
    { section: "widgets", tab: "clock", label: "Clock corner radius", highlight: "clock_size_radius", keywords: ["clock", "corner", "radius", "rounding"] },
    { section: "widgets", tab: "clock", label: "Clock opacity", highlight: "clock_size_opacity", keywords: ["clock", "opacity", "transparency"] },
    { section: "widgets", tab: "clock", label: "Clock anchor", highlight: "clock_placement_anchor", keywords: ["clock", "anchor", "placement", "position", "desktop"] },
    { section: "widgets", tab: "clock", label: "Clock position (X/Y)", highlight: "clock_placement_position", keywords: ["clock", "position", "x", "y", "coordinates", "drag"] },
    { section: "widgets", tab: "clock", label: "Lock clock on desktop", highlight: "clock_placement_lock", keywords: ["clock", "lock", "desktop", "drag"] },

    { section: "widgets", tab: "weather", label: "Weather widget location", highlight: "weather_location", keywords: ["weather", "location", "city", "desktop widget", "general"] },
    { section: "widgets", tab: "weather", label: "Weather widget enabled", highlight: "weather_widget_enabled", keywords: ["weather widget", "enable", "desktop weather"] },
    { section: "widgets", tab: "weather", label: "Weather widget design", highlight: "weather_widget_design", keywords: ["weather", "design", "card", "minimal", "strip"] },
    { section: "widgets", tab: "weather", label: "Weather widget unit", highlight: "weather_readout_unit", keywords: ["weather", "unit", "celsius", "fahrenheit", "temperature"] },
    { section: "widgets", tab: "weather", label: "Weather forecast scope", highlight: "weather_readout_scope", keywords: ["weather", "forecast", "today", "week"] },
    { section: "widgets", tab: "weather", label: "Weather live animations", highlight: "weather_readout_animate", keywords: ["weather", "animation", "live"] },
    { section: "widgets", tab: "weather", label: "Weather widget size", highlight: "weather_size_scale", keywords: ["weather", "size", "scale"] },
    { section: "widgets", tab: "weather", label: "Weather widget background", highlight: "weather_size_bg", keywords: ["weather", "background", "card", "glass"] },
    { section: "widgets", tab: "weather", label: "Weather widget corner radius", highlight: "weather_size_radius", keywords: ["weather", "corner", "radius"] },
    { section: "widgets", tab: "weather", label: "Weather widget opacity", highlight: "weather_size_opacity", keywords: ["weather", "opacity"] },
    { section: "widgets", tab: "weather", label: "Weather widget anchor", highlight: "weather_placement_anchor", keywords: ["weather", "anchor", "placement", "position", "desktop"] },
    { section: "widgets", tab: "weather", label: "Weather widget position (X/Y)", highlight: "weather_placement_position", keywords: ["weather", "position", "x", "y", "coordinates", "drag"] },
    { section: "widgets", tab: "weather", label: "Lock weather widget on desktop", highlight: "weather_placement_lock", keywords: ["weather", "lock", "desktop", "drag"] },

    { section: "widgets", tab: "calendar", label: "Calendar widget enabled", highlight: "cal_widget_enabled", keywords: ["calendar widget", "enable", "desktop calendar"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget design", highlight: "cal_widget_design", keywords: ["calendar", "design", "month", "minimal", "agenda", "week", "heatmap"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget accent", highlight: "cal_widget_accent", keywords: ["calendar", "accent", "colour"] },
    { section: "widgets", tab: "calendar", label: "Week starts on", highlight: "cal_week", keywords: ["calendar", "week", "start", "monday", "sunday"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget size", highlight: "cal_size_scale", keywords: ["calendar", "size", "scale"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget background", highlight: "cal_size_bg", keywords: ["calendar", "background", "card", "glass"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget corner radius", highlight: "cal_size_radius", keywords: ["calendar", "corner", "radius"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget opacity", highlight: "cal_size_opacity", keywords: ["calendar", "opacity"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget anchor", highlight: "cal_placement_anchor", keywords: ["calendar", "anchor", "placement", "position", "desktop"] },
    { section: "widgets", tab: "calendar", label: "Calendar widget position (X/Y)", highlight: "cal_placement_position", keywords: ["calendar", "position", "x", "y", "coordinates", "drag"] },
    { section: "widgets", tab: "calendar", label: "Lock calendar widget on desktop", highlight: "cal_placement_lock", keywords: ["calendar", "lock", "desktop", "drag"] },

    { section: "displays", tab: null, label: "Enabled", highlight: "display_enabled", keywords: ["disable", "turn off", "power state", "active display", "monitor on/off", "screen on"] },
    { section: "displays", tab: null, label: "Resolution", highlight: "display_resolution", keywords: ["mode", "screen size", "pixel dimensions", "display mode", "width height"] },
    { section: "displays", tab: null, label: "Scale", highlight: "display_scale", keywords: ["scaling", "dpi", "zoom", "hidpi", "display scale"] },
    { section: "displays", tab: null, label: "Rotation", highlight: "display_rotation", keywords: ["orientation", "rotate", "portrait", "landscape", "screen rotation"] },
    { section: "displays", tab: null, label: "Adaptive sync", highlight: "display_vrr", keywords: ["vrr", "variable refresh rate", "freesync", "g-sync", "tearing", "adaptive sync"] },
    { section: "displays", tab: null, label: "Mirror of", highlight: "display_mirror", keywords: ["mirror", "clone", "duplicate display", "screen mirroring"] },
    { section: "displays", tab: null, label: "Position X", highlight: "display_position_x", keywords: ["x coordinate", "placement", "monitor position", "layout position", "horizontal position"] },
    { section: "displays", tab: null, label: "Position Y", highlight: "display_position_y", keywords: ["y coordinate", "placement", "monitor position", "layout position", "vertical position"] },
    { section: "input", tab: null, label: "Layout", highlight: "keyboard_layout", keywords: ["keyboard layout", "xkb layout", "language layout", "locale", "keymap"] },
    { section: "input", tab: null, label: "Style", highlight: "keyboard_style", keywords: ["variant", "keyboard variant", "azerty", "dvorak", "layout style"] },
    { section: "input", tab: null, label: "Second layout", highlight: "keyboard_second_layout", keywords: ["secondary layout", "alternate keyboard", "multilingual", "second keymap"] },
    { section: "input", tab: null, label: "Switch layouts", highlight: "keyboard_switch", keywords: ["layout switch shortcut", "toggle layout", "language switch key", "keyboard switch chord"] },
    { section: "input", tab: null, label: "Numlock on at login", highlight: "keyboard_numlock", keywords: ["numlock", "number lock", "numeric keypad", "num lock default"] },
    { section: "input", tab: null, label: "Caps Lock", highlight: "key_remaps_capslock", keywords: ["capslock remap", "caps lock behavior", "escape remap", "ctrl remap"] },
    { section: "input", tab: null, label: "Swap Alt and Super", highlight: "key_remaps_swap", keywords: ["alt win swap", "super key", "windows key", "meta key", "command key swap"] },
    { section: "input", tab: null, label: "Compose key", highlight: "key_remaps_compose", keywords: ["compose key", "dead key", "special characters", "unicode input"] },
    { section: "input", tab: null, label: "Extra options", highlight: "key_remaps_extra", keywords: ["xkb options", "raw keyboard options", "advanced keyboard settings", "custom options"] },
    { section: "input", tab: null, label: "Sensitivity", highlight: "pointer_sensitivity", keywords: ["mouse speed", "pointer speed", "cursor speed", "mouse sensitivity"] },
    { section: "input", tab: null, label: "Follow mouse", highlight: "pointer_follow", keywords: ["focus follows mouse", "hover focus", "mouse focus", "sloppy focus"] },
    { section: "input", tab: null, label: "Acceleration", highlight: "pointer_accel", keywords: ["mouse acceleration", "pointer acceleration", "accel profile", "cursor acceleration"] },
    { section: "input", tab: null, label: "Left-handed buttons", highlight: "pointer_left_handed", keywords: ["left handed mouse", "button swap", "southpaw", "reverse buttons"] },
    { section: "input", tab: null, label: "Natural scroll (mouse)", highlight: "pointer_natural_scroll", keywords: ["reverse scrolling", "scroll direction", "invert scroll", "natural scrolling"] },
    { section: "input", tab: null, label: "Scroll speed (mouse)", highlight: "pointer_scroll_speed", keywords: ["mouse wheel speed", "scroll sensitivity", "wheel scroll speed"] },
    { section: "input", tab: null, label: "Middle-click pastes", highlight: "pointer_middle_click", keywords: ["middle click paste", "primary selection", "clipboard paste", "middle button paste"] },
    { section: "input", tab: null, label: "Natural scroll (touchpad)", highlight: "touchpad_natural_scroll", keywords: ["reverse scrolling", "scroll direction", "invert scroll", "natural scrolling"] },
    { section: "input", tab: null, label: "Tap to click", highlight: "touchpad_tap_click", keywords: ["tap click", "touchpad tap", "tap-to-click"] },
    { section: "input", tab: null, label: "Tap and drag", highlight: "touchpad_tap_drag", keywords: ["drag lock", "tap drag", "touchpad drag"] },
    { section: "input", tab: null, label: "Disable while typing", highlight: "touchpad_dwt", keywords: ["dwt", "palm rejection", "typing disable", "keyboard typing touchpad"] },
    { section: "input", tab: null, label: "Click by finger count", highlight: "touchpad_clickfinger", keywords: ["clickfinger", "two finger right click", "three finger middle click", "finger count click"] },
    { section: "input", tab: null, label: "Emulate middle click", highlight: "touchpad_middle_emulation", keywords: ["middle click emulation", "three finger click", "middle button emulation"] },
    { section: "input", tab: null, label: "Scroll speed (touchpad)", highlight: "touchpad_scroll_speed", keywords: ["touchpad scroll speed", "scroll sensitivity", "wheel scroll speed"] },
    { section: "input", tab: null, label: "Swipe between workspaces", highlight: "touchpad_swipe_enable", keywords: ["workspace swipe", "gesture navigation", "touchpad gestures", "workspace switching gesture"] },
    { section: "input", tab: null, label: "Swipe fingers", highlight: "touchpad_swipe_fingers", keywords: ["finger count", "gesture fingers", "3 finger 4 finger", "swipe finger count"] },
    { section: "input", tab: null, label: "Natural swipe direction", highlight: "touchpad_swipe_natural", keywords: ["swipe invert", "gesture direction", "natural gesture"] },
    { section: "input", tab: null, label: "Swipe past the last workspace to add one", highlight: "touchpad_swipe_create", keywords: ["create workspace swipe", "infinite workspaces", "new workspace gesture", "auto create workspace"] },
    { section: "input", tab: null, label: "Swipe distance", highlight: "touchpad_swipe_distance", keywords: ["gesture distance", "swipe threshold", "gesture sensitivity"] },
    { section: "input", tab: null, label: "Repeat rate", highlight: "key_repeat_rate", keywords: ["key repeat rate", "keyboard repeat speed", "autorepeat rate"] },
    { section: "input", tab: null, label: "Repeat delay", highlight: "key_repeat_delay", keywords: ["repeat delay", "key repeat delay", "initial delay", "autorepeat delay"] },
    { section: "input", tab: null, label: "Flip webcam 180°", highlight: "camera", keywords: ["webcam flip", "camera upside down", "camera orientation", "flip camera", "invert camera"] },
    { section: "connections", tab: "wifi", label: "Wi-Fi", highlight: "wifi_toggle", keywords: ["wifi on off", "wireless toggle", "wlan", "radio toggle", "wifi enable"] },
    { section: "connections", tab: "bluetooth", label: "Bluetooth", highlight: "bluetooth_toggle", keywords: ["bluetooth on off", "adapter toggle", "radio toggle", "wireless toggle", "bt enable"] },
    { section: "connections", tab: "hotspot", label: "Hotspot", highlight: "hotspot_toggle", keywords: ["hotspot on off", "wifi sharing", "tethering", "access point", "share connection"] },
    { section: "connections", tab: "hotspot", label: "Network name", highlight: "hotspot_name", keywords: ["ssid", "hotspot name", "wifi name", "network id"] },
    { section: "connections", tab: "hotspot", label: "Password", highlight: "hotspot_password", keywords: ["hotspot password", "wpa2 password", "wifi password", "shared key"] },
    { section: "gpu", tab: null, label: "Graphics mode", highlight: "renders_on", keywords: ["gpu mode", "hybrid performance passthrough", "graphics switching", "optimus", "prime", "gpu selection"] },
    { section: "recording", tab: null, label: "Framerate", highlight: "quality_framerate", keywords: ["fps", "frame rate", "video framerate", "recording fps"] },
    { section: "recording", tab: null, label: "Framerate mode", highlight: "quality_framerate_mode", keywords: ["cfr vfr", "constant framerate", "variable framerate", "frame rate mode"] },
    { section: "recording", tab: null, label: "Quality", highlight: "quality_quality", keywords: ["video quality", "bitrate", "recording quality", "encode quality"] },
    { section: "recording", tab: null, label: "Codec", highlight: "quality_codec", keywords: ["video codec", "h264 hevc av1", "compression format", "encoding format"] },
    { section: "recording", tab: null, label: "Encoder", highlight: "encoder_encoder", keywords: ["hardware encoder", "gpu cpu encoding", "video encoder", "encoding backend"] },
    { section: "recording", tab: null, label: "Show the cursor in recordings", highlight: "encoder_cursor", keywords: ["cursor recording", "mouse pointer capture", "show cursor", "record cursor"] },
    { section: "dictation", tab: null, label: "Voice typing", highlight: "dictation", keywords: ["dictation toggle", "voice typing on off", "speech to text enable", "voxtype enable"] },
    { section: "dictation", tab: null, label: "Engine & model", highlight: "engine_model", keywords: ["stt engine", "whisper model", "transcription engine", "voice model", "speech recognition engine"] },
    { section: "dictation", tab: null, label: "API key", highlight: "api_key", keywords: ["openai key", "api token", "credentials", "cloud engine key", "openai api key"] },

    { section: "updates", tab: null, label: "Automatic update checks", highlight: "auto_update_checks", keywords: ["update interval", "auto update", "check frequency", "schedule", "update schedule", "hourly", "daily", "weekly", "auto check", "update channel"] },

    { section: "appearance", tab: "look", label: "Corner radius", highlight: "look_shape_radius", keywords: ["radius", "rounding", "corner", "roundness", "window corners"] },
    { section: "appearance", tab: "look", label: "Corner softness", highlight: "look_shape_softness", keywords: ["rounding power", "corner curve", "squircle", "corner shape", "softness"] },
    { section: "appearance", tab: "look", label: "Border thickness", highlight: "look_shape_border", keywords: ["border width", "border size", "outline thickness", "window border"] },
    { section: "appearance", tab: "look", label: "Tiling layout", highlight: "look_shape_layout", keywords: ["layout", "dwindle", "master", "scrolling", "tiling mode", "window arrangement"] },
    { section: "appearance", tab: "look", label: "Column width", highlight: "look_shape_column_width", keywords: ["scrolling layout", "column size", "hyprscrolling", "width"] },
    { section: "appearance", tab: "look", label: "Scroll to follow focus", highlight: "look_shape_follow_focus", keywords: ["scrolling", "follow focus", "auto scroll", "hyprscrolling"] },
    { section: "appearance", tab: "look", label: "Inner gaps", highlight: "look_gaps_inner", keywords: ["gaps", "spacing", "window gap", "padding between windows", "inner gap"] },
    { section: "appearance", tab: "look", label: "Outer gaps", highlight: "look_gaps_outer", keywords: ["gaps", "screen edge", "monitor edge", "outer gap", "margin"] },
    { section: "appearance", tab: "look", label: "Drag to resize at window edges", highlight: "look_behaviour_resize", keywords: ["resize", "border drag", "window edge resize", "click drag resize"] },
    { section: "appearance", tab: "look", label: "Snap floating windows", highlight: "look_behaviour_snap", keywords: ["window snapping", "edge snap", "magnetism", "align windows"] },
    { section: "appearance", tab: "look", label: "Window title bars", highlight: "look_titlebars_enable", keywords: ["titlebar", "hyprbars", "window bar", "title bar"] },
    { section: "appearance", tab: "look", label: "Title bar height", highlight: "look_titlebars_height", keywords: ["titlebar height", "hyprbars", "bar size"] },
    { section: "appearance", tab: "look", label: "Title bar text size", highlight: "look_titlebars_text_size", keywords: ["titlebar font size", "text size", "hyprbars", "font"] },
    { section: "appearance", tab: "look", label: "Blur the title bar", highlight: "look_titlebars_blur", keywords: ["titlebar blur", "hyprbars", "blur"] },
    { section: "appearance", tab: "look", label: "Title bar buttons", highlight: "look_titlebars_buttons", keywords: ["window controls", "close button", "maximise button", "hyprbars"] },
    { section: "appearance", tab: "look", label: "Active window opacity", highlight: "look_opacity_active", keywords: ["opacity", "transparency", "focused window", "active opacity"] },
    { section: "appearance", tab: "look", label: "Inactive window opacity", highlight: "look_opacity_inactive", keywords: ["opacity", "transparency", "unfocused window", "inactive opacity"] },
    { section: "appearance", tab: "look", label: "Dim inactive windows", highlight: "look_opacity_dim", keywords: ["dimming", "unfocused dim", "inactive dim", "fade unfocused"] },
    { section: "appearance", tab: "look", label: "Dim strength", highlight: "look_opacity_dim_strength", keywords: ["dim amount", "dimming intensity", "inactive opacity", "unfocused darkness"] },
    { section: "appearance", tab: "look", label: "Blur enabled", highlight: "look_blur_enabled", keywords: ["window blur", "background blur", "toggle blur"] },
    { section: "appearance", tab: "look", label: "Blur size", highlight: "look_blur_size", keywords: ["blur radius", "blur amount", "blur strength"] },
    { section: "appearance", tab: "look", label: "Blur passes", highlight: "look_blur_passes", keywords: ["blur quality", "blur iterations", "blur passes"] },
    { section: "appearance", tab: "look", label: "X-ray", highlight: "look_blur_xray", keywords: ["xray blur", "see through blur", "wallpaper through blur", "transparent blur"] },
    { section: "appearance", tab: "look", label: "Blur vibrancy", highlight: "look_blur_vibrancy", keywords: ["blur saturation", "vibrancy", "colour intensity blur"] },
    { section: "appearance", tab: "look", label: "Blur noise", highlight: "look_blur_noise", keywords: ["grain", "blur noise", "texture", "dithering"] },
    { section: "appearance", tab: "look", label: "Window shadows", highlight: "look_depth_shadows", keywords: ["drop shadow", "shadow toggle", "window shadow"] },
    { section: "appearance", tab: "look", label: "Shadow range", highlight: "look_depth_shadow_range", keywords: ["shadow size", "shadow distance", "shadow spread"] },
    { section: "appearance", tab: "look", label: "Shadow sharpness", highlight: "look_depth_shadow_sharpness", keywords: ["shadow power", "shadow softness", "shadow falloff"] },
    { section: "appearance", tab: "look", label: "Animations", highlight: "look_depth_animations", keywords: ["animation toggle", "motion", "transitions", "enable animations"] },
    { section: "appearance", tab: "look", label: "Wobbly windows", highlight: "look_depth_wobbly", keywords: ["wobble", "jelly windows", "window wobble effect"] },
    { section: "appearance", tab: "look", label: "Open / close", highlight: "look_depth_open_close", keywords: ["open animation", "close animation", "pop", "slide", "gnome style", "window style"] },
    { section: "appearance", tab: "look", label: "Glow behind windows", highlight: "look_glow_enabled", keywords: ["glow effect", "window halo", "backlight glow"] },
    { section: "appearance", tab: "look", label: "Glow range", highlight: "look_glow_range", keywords: ["glow size", "glow distance", "halo size"] },
    { section: "appearance", tab: "look", label: "Glow colour", highlight: "look_glow_colour", keywords: ["glow color", "halo color"] },
    { section: "appearance", tab: "look", label: "Liquid glass windows", highlight: "look_glass_enabled", keywords: ["hyprglass", "glassmorphism", "glass effect", "frosted glass"] },
    { section: "appearance", tab: "look", label: "Glass preset", highlight: "look_glass_preset", keywords: ["hyprglass preset", "glass style", "clear", "subtle", "contrast"] },
    { section: "appearance", tab: "look", label: "Glass blur strength", highlight: "look_glass_blur_strength", keywords: ["hyprglass blur", "glass distortion"] },
    { section: "appearance", tab: "look", label: "Glass opacity", highlight: "look_glass_opacity", keywords: ["hyprglass opacity", "glass transparency"] },
    { section: "appearance", tab: "borders", label: "Active window border colour", highlight: "borders_colours_active", keywords: ["border color", "focused border", "active border color"] },
    { section: "appearance", tab: "borders", label: "Inactive window border colour", highlight: "borders_colours_inactive", keywords: ["border color", "unfocused border", "inactive border color"] },
    { section: "appearance", tab: "borders", label: "Rotating gradient border", highlight: "borders_animated_enable", keywords: ["gradient border", "rotating border", "rainbow border", "animated border"] },
    { section: "appearance", tab: "borders", label: "Rotation speed", highlight: "borders_animated_speed", keywords: ["gradient speed", "animated border speed", "border animation speed"] },
    { section: "appearance", tab: "borders", label: "Image border around windows", highlight: "borders_image_enable", keywords: ["imgborders", "picture border", "custom border image"] },
    { section: "appearance", tab: "borders", label: "Border scale", highlight: "borders_image_scale", keywords: ["imgborders", "border image size", "tiling scale"] },
    { section: "appearance", tab: "borders", label: "Smooth scaling", highlight: "borders_image_smooth", keywords: ["imgborders", "antialiasing", "smooth image", "filter"] },
    { section: "appearance", tab: "cursor", label: "Cursor theme", highlight: "cursor_theme_select", keywords: ["cursor icon set", "pointer theme", "icon theme"] },
    { section: "appearance", tab: "cursor", label: "Cursor size", highlight: "cursor_theme_size", keywords: ["pointer size", "cursor scale"] },
    { section: "appearance", tab: "cursor", label: "Hide after idle", highlight: "cursor_theme_idle", keywords: ["auto-hide cursor", "idle timeout", "hide pointer", "inactivity timeout", "cursor idle"] },
    { section: "appearance", tab: "cursor", label: "Hide while typing", highlight: "cursor_theme_hide_typing", keywords: ["auto-hide on keypress", "pointer hide typing", "cursor hide typing"] },
    { section: "appearance", tab: "cursor", label: "Realistic cursor motion", highlight: "cursor_motion_enable", keywords: ["dynamiccursors", "cursor animation", "physics cursor"] },
    { section: "appearance", tab: "cursor", label: "Cursor motion style", highlight: "cursor_motion_style", keywords: ["rotate", "tilt", "stretch", "dynamiccursors", "pointer style"] },
    { section: "appearance", tab: "cursor", label: "Shake to find", highlight: "cursor_motion_shake", keywords: ["magnify cursor", "find my cursor", "shake mouse", "cursor locate"] },
    { section: "appearance", tab: "wallpaper", label: "Theme palette colours", highlight: "wallpaper_palette", keywords: ["colour scheme", "light dark", "follow wallpaper", "wallust", "palette mode"] },
    { section: "appearance", tab: "comfort", label: "Backlight brightness", highlight: "comfort_backlight", keywords: ["backlight", "display brightness", "panel brightness", "screen brightness"] },
    { section: "appearance", tab: "comfort", label: "Vibrance saturation", highlight: "comfort_vibrance", keywords: ["saturation", "colour intensity", "screen vibrance"] },
    { section: "appearance", tab: "comfort", label: "Warm the screen", highlight: "comfort_night_enable", keywords: ["blue light filter", "warm screen", "redshift", "night light", "nightlight"] },
    { section: "appearance", tab: "comfort", label: "Night light temperature", highlight: "comfort_night_temp", keywords: ["colour temperature", "warmth", "kelvin", "blue light"] },

    { section: "launcher", tab: null, label: "Corner radius", highlight: "shape_corner_radius", keywords: ["radius", "rounding", "corner", "launcher shape"] },
    { section: "launcher", tab: null, label: "Background blur", highlight: "background_blur", keywords: ["backdrop blur", "launcher blur", "blur amount"] },
    { section: "launcher", tab: null, label: "Weather units", highlight: "home_card_weather_units", keywords: ["celsius", "fahrenheit", "temperature unit", "weather"] },
    { section: "launcher", tab: null, label: "Show weather", highlight: "home_card_show_weather", keywords: ["weather widget", "home card weather"] },
    { section: "launcher", tab: null, label: "Show greeting", highlight: "home_card_show_greeting", keywords: ["greeting message", "welcome text", "home card greeting"] },
    { section: "launcher", tab: null, label: "Backdrop strength", highlight: "backdrop_strength", keywords: ["hero image opacity", "backdrop opacity", "launcher background strength"] },

    { section: "fastfetch", tab: null, label: "Emblem type", highlight: "emblem_type", keywords: ["logo type", "image", "ascii", "builtin", "none", "fastfetch logo"] },
    { section: "fastfetch", tab: null, label: "Logo width", highlight: "emblem_width", keywords: ["fastfetch logo size", "emblem width"] },
    { section: "fastfetch", tab: null, label: "Logo height", highlight: "emblem_height", keywords: ["fastfetch logo size", "emblem height"] },
    { section: "fastfetch", tab: null, label: "Logo padding", highlight: "emblem_padding", keywords: ["fastfetch logo spacing", "emblem padding"] },
    { section: "fastfetch", tab: null, label: "Readout accent", highlight: "accent", keywords: ["fastfetch colour", "accent colour", "terminal readout colour"] },

    { section: "animations", tab: null, label: "Animations", highlight: "global", keywords: ["animation toggle", "enable animations", "motion", "transitions", "global animations"] },
    { section: "animations", tab: null, label: "Animate the focused window", highlight: "focus_flash_enable", keywords: ["hyprfocus", "focus animation", "window focus effect", "focus flash"] },
    { section: "animations", tab: null, label: "Focus flash style", highlight: "focus_flash_style", keywords: ["flash", "bounce", "slide", "hyprfocus mode"] },
    { section: "animations", tab: null, label: "Flash opacity", highlight: "focus_flash_opacity", keywords: ["hyprfocus", "focus flash intensity"] },
    { section: "animations", tab: null, label: "Bounce strength", highlight: "focus_flash_bounce", keywords: ["hyprfocus", "focus bounce amount"] },
    { section: "animations", tab: null, label: "Slide height", highlight: "focus_flash_slide", keywords: ["hyprfocus", "focus slide distance"] },

    { section: "addons", tab: null, label: "Enable/disable plugin", highlight: "addon_enabled", keywords: ["addon", "add-on", "plugin", "enable", "disable", "toggle on", "widget", "extension"] },
    { section: "addons", tab: null, label: "Show as", highlight: "addon_show_as", keywords: ["host", "placement", "frame popout", "desktop widget", "widget location", "display as", "popout"] },
    { section: "windowrules", tab: null, label: "Window rules", keywords: ["float", "tile", "pin", "fullscreen", "maximize", "center", "size", "move", "workspace", "opacity", "blur", "border", "shadow", "rounding", "corners", "dim", "animations", "opaque", "xray", "focus", "idle", "sleep", "class", "title", "match window", "custom rule"] },
    { section: "appoverrides", tab: null, label: "App overrides", keywords: ["per-app", "per application", "class", "title", "match window", "window rule", "override", "app-specific", "custom look"] },
    { section: "appoverrides", tab: null, label: "Opacity", keywords: ["transparency", "alpha", "translucent", "see-through"] },
    { section: "appoverrides", tab: null, label: "Corners", keywords: ["radius", "rounding", "corner", "roundness", "round corners"] },
    { section: "appoverrides", tab: null, label: "Border", keywords: ["border size", "outline", "edge", "border width", "stroke"] },
    { section: "appoverrides", tab: null, label: "Blur", keywords: ["backdrop blur", "background blur", "frosted glass"] },
    { section: "appoverrides", tab: null, label: "Shadow", keywords: ["drop shadow", "window shadow"] },
    { section: "appoverrides", tab: null, label: "Dim inactive", keywords: ["dim", "inactive window", "unfocused", "darken", "fade unfocused"] },
    { section: "appoverrides", tab: null, label: "Animations", keywords: ["animation", "motion", "transition", "noanim"] },
    { section: "appoverrides", tab: null, label: "Force opaque", keywords: ["opaque", "force opacity", "remove transparency", "solid background"] },
    { section: "layerrules", tab: null, label: "Layer rules", keywords: ["namespace", "bar", "launcher", "notification", "layer shell", "blur", "dim around", "lockscreen", "above lock", "xray", "ignore alpha", "surface"] },
    { section: "autostart", tab: null, label: "Autostart", keywords: ["startup", "login", "boot", "launch at start", "run on login", "startup command", "autostart command"] },
    { section: "environment", tab: null, label: "Environment variables", keywords: ["env var", "environment variable", "export", "name value pair", "session variable"] },
    { section: "performance", tab: null, label: "Low power mode", highlight: "low_power_mode", keywords: ["potato mode", "battery saver", "low power", "performance mode", "reduce effects", "laptop battery", "weak gpu"] },
    { section: "performance", tab: null, label: "Reduce motion", highlight: "reduce_motion", keywords: ["motion", "animation", "transitions", "instant", "accessibility", "reduce animation"] },
    { section: "performance", tab: null, label: "Disable blur", highlight: "disable_blur", keywords: ["blur off", "backdrop blur", "gpu", "turn off blur", "no blur"] },
    { section: "performance", tab: null, label: "Disable shadows", highlight: "disable_shadows", keywords: ["shadow off", "drop shadow", "no shadow", "window shadow"] },
    { section: "performance", tab: null, label: "Hide desktop widgets while covered", highlight: "desktop_widgets", keywords: ["desktop widget", "memory", "unload widget", "hide widget", "covered windows", "free memory"] },
    { section: "performance", tab: null, label: "Freeze visualiser when idle", highlight: "visualiser_freeze", keywords: ["audio visualizer", "spectrum", "waveform", "freeze animation", "idle", "no audio"] },
    { section: "performance", tab: null, label: "Unload visualiser when silent", highlight: "visualiser_unload", keywords: ["audio visualizer", "memory", "unload", "silent", "no audio", "free memory"] },
    { section: "performance", tab: null, label: "Freeze bar bead animation", highlight: "bar", keywords: ["glowing bead", "bar animation", "pill animation", "idle bar", "statusbar"] },
    { section: "performance", tab: null, label: "Unload launcher when idle", highlight: "launcher_overview_launcher", keywords: ["app launcher", "memory", "unload", "idle", "free memory", "drun"] },
    { section: "performance", tab: null, label: "Unload overview when idle", highlight: "launcher_overview_overview", keywords: ["workspace overview", "memory", "unload", "idle", "free memory", "expo", "overview mode"] },
    { section: "rashin", tab: null, label: "Start Rashin with desktop", highlight: "enable", keywords: ["rashin daemon", "agent os", "enable rashin", "local agent", "vault", "enable daemon", "autostart daemon"] },
    { section: "keybinds", tab: "custom", label: "Custom keybinds", keywords: ["shortcut", "hotkey", "bind", "keybind", "hyprland bind", "custom shortcut", "key combo"] }
];
